[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

# Tell Foundry to load the variables from our .env file
dotenv = [".env"]

# Configure Etherscan for verification
[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}", chain = 17000 }

# Configure RPC endpoints
[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"